using System.ComponentModel.DataAnnotations;

namespace Spira.Text
{
    public enum FFXTextTagArea : byte
    {
        noname2 = 0x30,
        Zanarkand = 0x31,
        ZanarkandRuins = 0x32,
        Spira = 0x33,
        Baaj = 0x34,
        BaajIsland = 0x35,
        TempleofYevonBaaj = 0x36,
        BaajTemple = 0x37,
        Besaid = 0x38,
        BesaidIsland = 0x39,
        BesaidVillage = 0x3A,
        TempleofYevonBesaid = 0x3B,
        BesaidTemple = 0x3C,
        ChamberoftheFayth = 0x3D,
        SSLiki=0x3E,
        Kilika = 0x3F,
        KilikaIsland = 0x40,
        KilikaPort = 0x41,
        KilikaWoods = 0x42,
        TempleofYevonKilika = 0x43,
        KilikaTemple = 0x44,
        SSWinno=0x45,
        Djose = 0x46,
        DjoseContinent = 0x47,
        Luca = 0x48,
        LucaSeaport = 0x49,
        LucaStadium = 0x4A,
        BlitzballStadium = 0x4B,
        MiihenHighroad = 0x4C,
        MiihenNewroad = 0x4D,
        MiihenOldroad = 0x4E,
        MiihenHighroadsEnd = 0x4F,
        RinTravelAgency = 0x50,
        MushroomRockRoad = 0x51,
        TempleofYevonDjose = 0x52,
        DjoseTemple = 0x53,
        Moonflow = 0x54,
        Guadosalam = 0x55,
        Farplane = 0x56,
        BilghenPlains = 0x57,
        ThunderPlains = 0x58,
        Macalania = 0x59,
        MacalaniaWoods = 0x5A,
        LakeMacalania = 0x5B,
        TempleofYevonMacalania = 0x5C,
        MacalaniaTemple = 0x5D,
        Bikanel = 0x5E,
        BikanelIsland = 0x5F,
        SanubiaDesert = 0x60,
        Home2 = 0x61,
        Home3 = 0x62,
        Bevelle = 0x63,
        StBevelle = 0x64,
        TempleofYevonBevelle = 0x65,
        BevelleTemple = 0x66,
        Highbridge = 0x67,
        FrostWilds = 0x68,
        CalmLands = 0x69,
        Gagazet = 0x6A,
        MtGagazet = 0x6B,
        Dome = 0x6C,
    }
}